kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-cert
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
